export { timeStrategy } from './timeStrategy'
export { dateStrategy } from './dateStrategy'
export { fileStrategy } from './fileStrategy'
export { inputStrategy } from './inputStrategy'
export { selectStrategy } from './selectStrategy'
export { dateTimeStrategy } from './dateTimeStrategy'
